const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
  windowMinimize:   ()                                  => ipcRenderer.invoke('window-minimize'),
  windowMaximize:   ()                                  => ipcRenderer.invoke('window-maximize'),
  windowClose:      ()                                  => ipcRenderer.invoke('window-close'),
  selectFolder:     ()                                  => ipcRenderer.invoke('select-folder'),
  scanFolders:      (folders, excluded, settings)       => ipcRenderer.invoke('scan-folders', folders, excluded, settings),
  // Keys are no longer passed as args — main reads them from encrypted storage.
  fetchMetadata:    (item)                              => ipcRenderer.invoke('fetch-metadata', item),
  saveLibrary:      (lib)                               => ipcRenderer.invoke('save-library', lib),
  loadLibrary:      ()                                  => ipcRenderer.invoke('load-library'),
  loadApiKeys:      ()                                  => ipcRenderer.invoke('load-api-keys'),
  saveApiKeys:      (keys)                              => ipcRenderer.invoke('save-api-keys', keys),
  openFile:         (p)                                 => ipcRenderer.invoke('open-file', p),
  clearItemCache:   (ids)                               => ipcRenderer.invoke('clear-item-cache', ids),
  openExternal:     (url)                               => ipcRenderer.invoke('open-external', url),
  getAppVersion:    ()                                  => ipcRenderer.invoke('get-app-version'),
  checkFilesExist:  (data)                              => ipcRenderer.invoke('check-files-exist', data),
  saveFile:         (opts)                              => ipcRenderer.invoke('save-file', opts),
  readFile:         (opts)                              => ipcRenderer.invoke('read-file', opts),
  revealFile:       (p)                                 => ipcRenderer.invoke('reveal-file', p),
  getPlatform:      ()                                  => ipcRenderer.invoke('get-platform'),
  fetchHeadshots:   (cast, crew)                        => ipcRenderer.invoke('fetch-headshots', cast, crew),
  // Key args removed — main reads keys internally.
  searchPerson:     (name)                              => ipcRenderer.invoke('search-person', name),
  getWatchProviders:(tmdbId, type, country)             => ipcRenderer.invoke('get-watch-providers', tmdbId, type, country),
  fetchFilmPosters: (films)                             => ipcRenderer.invoke('fetch-film-posters', films),
  remapSearch:      (query, type)                       => ipcRenderer.invoke('remap-search', query, type),
  remapApply:       (item, tmdbId, type)                => ipcRenderer.invoke('remap-apply', item, tmdbId, type),
  searchTitle:      (query)                             => ipcRenderer.invoke('search-title', query),
  fetchTitleDetail: (id, type, country)                 => ipcRenderer.invoke('fetch-title-detail', id, type, country),
  tmdbGet:          (pathAndQuery)                       => ipcRenderer.invoke('tmdb-get', pathAndQuery),
});
