const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
  windowMinimize:   ()                                  => ipcRenderer.invoke('window-minimize'),
  windowMaximize:   ()                                  => ipcRenderer.invoke('window-maximize'),
  windowClose:      ()                                  => ipcRenderer.invoke('window-close'),
  selectFolder:     ()                                  => ipcRenderer.invoke('select-folder'),
  scanFolders:      (folders, excluded, settings)       => ipcRenderer.invoke('scan-folders', folders, excluded, settings),
  fetchMetadata:    (item, tKey, oKey)                  => ipcRenderer.invoke('fetch-metadata', item, tKey, oKey),
  saveLibrary:      (lib)                               => ipcRenderer.invoke('save-library', lib),
  loadLibrary:      ()                                  => ipcRenderer.invoke('load-library'),
  openFile:         (p)                                 => ipcRenderer.invoke('open-file', p),
  clearItemCache:   (ids)                                => ipcRenderer.invoke('clear-item-cache', ids),
  checkFilesExist:  (data)                               => ipcRenderer.invoke('check-files-exist', data),
  saveFile:         (opts)                               => ipcRenderer.invoke('save-file', opts),
  readFile:         (opts)                               => ipcRenderer.invoke('read-file', opts),
  revealFile:       (p)                                 => ipcRenderer.invoke('reveal-file', p),
  getPlatform:      ()                                  => ipcRenderer.invoke('get-platform'),
  fetchHeadshots:   (cast, crew)                        => ipcRenderer.invoke('fetch-headshots', cast, crew),
  searchPerson:     (name, key)                         => ipcRenderer.invoke('search-person', name, key),
  getWatchProviders:(tmdbId, type, key, country)        => ipcRenderer.invoke('get-watch-providers', tmdbId, type, key, country),
  fetchFilmPosters: (films)                             => ipcRenderer.invoke('fetch-film-posters', films),
  remapSearch:      (query, type, key)                  => ipcRenderer.invoke('remap-search', query, type, key),
  remapApply:       (item, tmdbId, type, tKey, oKey)    => ipcRenderer.invoke('remap-apply', item, tmdbId, type, tKey, oKey),
  searchTitle:      (query, tKey, oKey)                 => ipcRenderer.invoke('search-title', query, tKey, oKey),
  fetchTitleDetail: (id, type, tKey, oKey, country)     => ipcRenderer.invoke('fetch-title-detail', id, type, tKey, oKey, country),
});
